# Generated by Django 6.0 on 2025-12-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('house', 'House'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], default='house', max_length=20),
            preserve_default=False,
        ),
    ]
