# Generated by Django 6.0 on 2025-12-07 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='houseimage',
            options={'ordering': ['-is_primary', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma-separated amenities', max_length=500),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_phone',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('standalone', 'Stand Alone House'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('roommate', 'Roommate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(help_text='Detailed description of the property'),
        ),
        migrations.AlterField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(help_text='Address/Area', max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent in KSh', max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(help_text='Property name/title', max_length=200),
        ),
    ]
