# Generated by Django 6.0 on 2025-12-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_options_alter_houseimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='available_units',
            field=models.PositiveIntegerField(default=1, help_text='Currently available units'),
        ),
        migrations.AddField(
            model_name='house',
            name='total_units',
            field=models.PositiveIntegerField(default=1, help_text='Total number of units/apartments available'),
        ),
    ]
