# Generated by Django 6.0 on 2025-12-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('movers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(help_text='Current location (where items are being moved from)', max_length=300)),
                ('dropoff_location', models.CharField(help_text='New location (where items are being moved to)', max_length=300)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=8)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base rate from mover', max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=50, help_text='Rate per km', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost (base_rate + distance_km * rate_per_km)', max_digits=10)),
                ('mover_rating', models.DecimalField(decimal_places=1, default=0, help_text="Mover's average rating at booking time", max_digits=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mover_booking', to='booking.booking')),
                ('mover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movers.moverservice')),
            ],
        ),
    ]
