# Generated by Django 6.0 on 2025-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moverservice',
            name='base_rate',
        ),
        migrations.AddField(
            model_name='moverservice',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Charge per kilometer', max_digits=10),
        ),
    ]
